"use strict";
const $=s=>document.querySelector(s),storageKey="thienHaXanhMembersV1";
const roles={leader:{name:"Nhóm trưởng",icon:"★"},deputy:{name:"Nhóm phó",icon:"◆"},member:{name:"Thành viên",icon:"●"}};
let members=load(),activeRole="all",view="cards",tempPhoto=null;
function load(){try{const value=JSON.parse(localStorage.getItem(storageKey));if(Array.isArray(value))return value.map(m=>({...m,membership:m.membership||"volunteer"}))}catch{}return[]}function save(){localStorage.setItem(storageKey,JSON.stringify(members));window.cloudSave?.(members)}
function initials(name){return name.trim().split(/\s+/).slice(-2).map(x=>x[0]).join("").toUpperCase()}
function escapeHtml(text){const d=document.createElement("div");d.textContent=text;return d.innerHTML}
function normalize(text){return text.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase()}
function visibleMembers(){const result=[...members],accounts=window.approvedManagerProfiles||[];for(const account of accounts){if(!result.some(m=>m.role===account.role))result.push({id:`account-${account.role}`,name:account.display_name,studentId:"",role:account.role,membership:"management",className:"Chưa cập nhật",faculty:"Tài khoản quản lý nhóm",phone:"",photo:null,virtual:true})}return result}
function filtered(){const q=normalize($("#searchInput").value),role=$("#roleFilter").value,membership=$("#membershipFilter").value;return visibleMembers().filter(m=>(activeRole==="all"||m.role===activeRole)&&(role==="all"||m.role===role)&&(membership==="all"||m.membership===membership||m.virtual)&&(!q||normalize(`${m.name} ${m.studentId||""} ${m.className} ${m.faculty} ${m.phone}`).includes(q))).sort((a,b)=>({leader:0,deputy:1,member:2}[a.role]-{leader:0,deputy:1,member:2}[b.role]||a.name.localeCompare(b.name,"vi")))}
function render(){const list=filtered(),accounts=window.approvedManagerProfiles||[],leaderAccount=accounts.find(a=>a.role==="leader"),deputyAccount=accounts.find(a=>a.role==="deputy"),leader=members.find(m=>m.role==="leader")||(leaderAccount&&{name:leaderAccount.display_name}),deputy=members.find(m=>m.role==="deputy")||(deputyAccount&&{name:deputyAccount.display_name}),leaderCount=Math.max(members.filter(m=>m.role==="leader").length,accounts.filter(a=>a.role==="leader").length),deputyCount=Math.max(members.filter(m=>m.role==="deputy").length,accounts.filter(a=>a.role==="deputy").length),memberCount=members.filter(m=>m.role==="member").length,totalCount=leaderCount+deputyCount+memberCount;$("#total").textContent=totalCount;$("#volunteerCount").textContent=members.filter(m=>m.membership==="volunteer").length;$("#leaderName").textContent=leader?.name||"Chưa có";$("#deputyName").textContent=deputy?.name||"Chưa có";$("#allBadge").textContent=totalCount;$("#leaderBadge").textContent=leaderCount;$("#deputyBadge").textContent=deputyCount;$("#memberBadge").textContent=memberCount;$("#resultInfo").textContent=`Hiển thị ${list.length} hồ sơ · Tổng nhóm ${totalCount} người`;const box=$("#memberList");box.className=`member-grid ${view==="table"?"table-view":""}`;box.innerHTML=list.length?list.map(card).join(""):`<div class="empty">Chưa có hồ sơ thành viên trong danh sách.</div>`}
function card(m){const membership=m.virtual?"Tài khoản quản lý":m.membership==="association"?"Hội viên":"Tình nguyện viên",cover=m.photo?`<div class="member-cover" style="background-image:url('${m.photo}')"></div>`:`<div class="member-cover empty"></div>`,canEdit=!m.virtual&&(window.canManageMembers||m.authUserId===window.currentUserId),actions=canEdit?`<div class="card-actions"><button data-action="edit" data-id="${m.id}" title="Chỉnh sửa hồ sơ">✎</button>${window.canManageMembers?`<button data-action="delete" data-id="${m.id}" title="Xóa">🗑</button>`:""}</div>`:"",link=!m.virtual&&!m.authUserId&&window.canManageMembers?`<span class="invite-code">Mã liên kết: <b>${escapeHtml(m.inviteCode||"")}</b></span>`:"",phone=m.phone?`<a class="phone" href="tel:${m.phone.replace(/\s/g,"")}">${escapeHtml(m.phone)}</a>`:"Chưa cập nhật";return`<article class="member-card ${m.role}">${cover}<div class="person"><span class="avatar">${initials(m.name)}</span><div><h3>${escapeHtml(m.name)}</h3><span class="role">${roles[m.role].icon} ${roles[m.role].name}</span></div></div><span class="membership ${m.membership}">${m.virtual?"🔐":m.membership==="volunteer"?"🩸":"♥"} ${membership}</span>${link}<div class="info"><span><i>🪪</i><b>MSSV: ${escapeHtml(m.studentId||"Chưa cập nhật")}</b></span><span><i>🏫</i><b>${escapeHtml(m.className||"Chưa cập nhật")}</b></span><span><i>🎓</i><span>${escapeHtml(m.faculty||"Chưa cập nhật")}</span></span><span><i>☎</i>${phone}</span></div>${actions}</article>`}
function openForm(m=null){const own=m?.authUserId===window.currentUserId;if(!window.canManageMembers&&!own)return toast("Bạn chỉ có thể sửa hồ sơ của mình");const dialog=$("#memberDialog");$("#memberForm").reset();$("#editId").value=m?.id||"";$("#formTitle").textContent=m?"Sửa thành viên":"Thêm thành viên";$("#fullName").value=m?.name||"";$("#studentId").value=m?.studentId||"";$("#role").value=m?.role||"member";$("#membership").value=m?.membership||"volunteer";$("#role").disabled=!window.canManageMembers;$("#membership").disabled=!window.canManageMembers;$("#className").value=m?.className||"";$("#faculty").value=m?.faculty||"";$("#phone").value=m?.phone||"";tempPhoto=m?.photo||null;showPhotoPreview();try{if(!dialog.open)dialog.showModal()}catch{dialog.setAttribute("open","")}setTimeout(()=>$("#fullName").focus(),100)}
function submit(e){e.preventDefault();const id=$("#editId").value,old=members.find(m=>m.id===id),member={id:id||crypto.randomUUID(),name:$("#fullName").value.trim(),studentId:$("#studentId").value.trim(),role:old&&!window.canManageMembers?old.role:$("#role").value,membership:old&&!window.canManageMembers?old.membership:$("#membership").value,className:$("#className").value.trim(),faculty:$("#faculty").value.trim(),phone:$("#phone").value.trim(),photo:tempPhoto,authUserId:old?.authUserId||null,inviteCode:old?.inviteCode||crypto.randomUUID().slice(0,8).toUpperCase()};if(["leader","deputy"].includes(member.role)){const existing=members.find(m=>m.role===member.role&&m.id!==id);if(existing&&!confirm(`Hiện ${existing.name} đang là ${roles[member.role].name}. Chuyển người này thành thành viên và thay thế?`))return;if(existing)existing.role="member"}if(id){const index=members.findIndex(m=>m.id===id);members[index]=member}else members.push(member);save();$("#memberDialog").close();render();toast(id?"Đã cập nhật thành viên":"Đã thêm thành viên")}
function showPhotoPreview(){const preview=$("#photoPreview");preview.style.backgroundImage=tempPhoto?`url('${tempPhoto}')`:"";preview.classList.toggle("has-photo",Boolean(tempPhoto));$("#removePhoto").hidden=!tempPhoto}
function compressPhoto(file){return new Promise((resolve,reject)=>{if(!file.type.startsWith("image/"))return reject(new Error("File không phải hình ảnh"));const reader=new FileReader();reader.onerror=()=>reject(new Error("Không đọc được ảnh"));reader.onload=()=>{const image=new Image();image.onerror=()=>reject(new Error("Ảnh không hợp lệ"));image.onload=()=>{const maxWidth=900,maxHeight=500,scale=Math.min(1,maxWidth/image.width,maxHeight/image.height),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));canvas.getContext("2d").drawImage(image,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL("image/jpeg",.72))};image.src=reader.result};reader.readAsDataURL(file)})}
async function choosePhoto(e){const file=e.target.files[0];if(!file)return;try{tempPhoto=await compressPhoto(file);showPhotoPreview();toast("Đã chọn và nén ảnh")}catch(error){alert(error.message)}finally{e.target.value=""}}
function listAction(e){const b=e.target.closest("button[data-action]");if(!b)return;const m=members.find(x=>x.id===b.dataset.id);if(b.dataset.action==="edit")openForm(m);else if(confirm(`Xóa ${m.name} khỏi nhóm?`)){members=members.filter(x=>x.id!==m.id);save();render();toast("Đã xóa thành viên")}}
function exportCSV(){if(!members.length)return toast("Danh sách đang trống");const rows=[["Họ và tên","Mã sinh viên","Vai trò","Đối tượng","Lớp","Khoa","Số điện thoại"],...members.map(m=>[m.name,m.studentId||"",roles[m.role].name,m.membership==="association"?"Hội viên":"Tình nguyện viên",m.className,m.faculty,m.phone])],csv="\uFEFF"+rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download="thanh-vien-thien-ha-xanh.csv";a.click();URL.revokeObjectURL(a.href)}
function toast(text){$("#toast").textContent=text;$("#toast").classList.add("show");setTimeout(()=>$("#toast").classList.remove("show"),2200)}
$("#photoInput").addEventListener("change",choosePhoto);$("#removePhoto").onclick=()=>{tempPhoto=null;showPhotoPreview();toast("Đã xóa ảnh khỏi hồ sơ")};
$("#addButton").onclick=$("#mobileAdd").onclick=()=>openForm();$("#memberForm").onsubmit=submit;document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>$("#memberDialog").close());$("#memberList").onclick=listAction;$("#searchInput").oninput=render;$("#roleFilter").onchange=render;$("#membershipFilter").onchange=render;document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{activeRole=b.dataset.role;document.querySelectorAll(".filter").forEach(x=>x.classList.toggle("active",x===b));render()});document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelectorAll("[data-view]").forEach(x=>x.classList.toggle("active",x===b));render()});$("#exportButton").onclick=exportCSV;$("#fullscreen").onclick=async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}catch{}};if("serviceWorker"in navigator&&location.protocol!=="file:")navigator.serviceWorker.register("service-worker.js");render();
