"use strict";
{
const config=window.SUPABASE_CONFIG||{},sessionKey="thienHaXanhCloudSession",memberKey="thienHaXanhMembersV1";let session=null,profile=null,appLoaded=false;
const inviteParams=new URLSearchParams(location.search),managerInviteToken=(inviteParams.get("manager_invite")||"").trim(),managerInviteRole=inviteParams.get("role");
const $=s=>document.querySelector(s),configured=()=>/^https:\/\/.+\.supabase\.co$/.test(config.url)&&config.anonKey&&!config.anonKey.startsWith("PASTE_");
const headers=token=>({apikey:config.anonKey,Authorization:`Bearer ${token}`,"Content-Type":"application/json"});
function message(text,ok=false){$("#loginMessage").textContent=text;$("#loginMessage").classList.toggle("success",ok)}
async function request(path,options={}){const response=await fetch(config.url+path,{...options,headers:{...headers(session?.access_token||config.anonKey),...(options.headers||{})}});if(!response.ok){const e=await response.json().catch(()=>({message:"Lỗi kết nối"}));throw new Error(e.message||e.error_description||e.msg||`HTTP ${response.status}`)}if(response.status===204)return null;const text=await response.text();return text?JSON.parse(text):null}
window.thxCloudRequest=request;
async function signIn(email,password){const response=await fetch(`${config.url}/auth/v1/token?grant_type=password`,{method:"POST",headers:{apikey:config.anonKey,"Content-Type":"application/json"},body:JSON.stringify({email,password})}),result=await response.json();if(!response.ok)throw new Error(result.error_description||result.msg||"Đăng nhập thất bại");session=result;localStorage.setItem(sessionKey,JSON.stringify(session));await enterApp()}
async function signUp(name,email,password,role,extra={}){const response=await fetch(`${config.url}/auth/v1/signup`,{method:"POST",headers:{apikey:config.anonKey,"Content-Type":"application/json"},body:JSON.stringify({email,password,data:{display_name:name,requested_role:role,...extra}})}),result=await response.json();if(!response.ok)throw new Error(result.error_description||result.msg||"Không thể đăng ký");return result}
function statusError(status){return status==="pending"?"Tài khoản đang chờ admin duyệt.":status==="rejected"?"Tài khoản đã bị từ chối. Hãy liên hệ admin.":status==="locked"?"Tài khoản đang bị khóa.":"Tài khoản chưa được cấp quyền."}
async function enterApp(){profile=(await request(`/rest/v1/manager_profiles?user_id=eq.${session.user.id}&select=user_id,display_name,email,role,status,requested_role`))[0];if(!profile||profile.status!=="approved"||!["admin","leader","deputy","member"].includes(profile.role)){const reason=statusError(profile?.status);localStorage.removeItem(sessionKey);session=null;throw new Error(reason)}let managers;try{managers=await request("/rest/v1/manager_profiles?status=eq.approved&role=in.(leader,deputy)&select=user_id,display_name,role,status,student_id,class_name,faculty,phone,photo,membership")}catch{managers=await request("/rest/v1/manager_profiles?status=eq.approved&role=in.(leader,deputy)&select=user_id,display_name,role,status")}const rows=await request("/rest/v1/members?select=*&order=created_at.asc"),members=rows.map(r=>({id:r.id,name:r.name,studentId:r.student_id||"",role:r.role,membership:r.membership,className:r.class_name,faculty:r.faculty,phone:r.phone,photo:r.photo,authUserId:r.auth_user_id,inviteCode:r.invite_code}));localStorage.setItem(memberKey,JSON.stringify(members));window.currentManagerProfile=profile;window.approvedManagerProfiles=managers;window.canManageMembers=["admin","leader","deputy"].includes(profile.role);window.currentUserId=session.user.id;const roleName={admin:"Admin",leader:"Nhóm trưởng",deputy:"Nhóm phó",member:"Thành viên"}[profile.role];$("#accountInfo").textContent=`${profile.display_name} · ${roleName}`;$("#adminButton").hidden=profile.role!=="admin";$("#addButton").hidden=!window.canManageMembers;$("#mobileAdd").hidden=!window.canManageMembers;$("#notificationForm").hidden=!window.canManageMembers;$("#loginScreen").classList.add("hidden");$(".app").classList.add("ready");await refreshNotificationBadge();if(!appLoaded){appLoaded=true;const script=document.createElement("script");script.src="app.js";document.body.appendChild(script)}}
async function loadAccounts(){const rows=await request("/rest/v1/manager_profiles?role=in.(leader,deputy)&select=user_id,display_name,email,role,status,created_at&order=created_at.asc");$("#accountList").innerHTML=rows.length?rows.map(a=>`<article class="account-row"><div><b>${escapeHtml(a.display_name)}</b><small>${escapeHtml(a.email||"")} · ${a.role==="leader"?"Nhóm trưởng":"Nhóm phó"}</small><span class="status ${a.status}">${{pending:"Chờ duyệt",approved:"Đã duyệt",rejected:"Từ chối",locked:"Đã khóa"}[a.status]}</span></div><div>${a.status!=="approved"?`<button class="approve" data-account="${a.user_id}" data-status="approved">Duyệt</button>`:`<button data-account="${a.user_id}" data-status="locked">Khóa</button>`}<button class="reject" data-account="${a.user_id}" data-status="rejected">Từ chối</button></div></article>`).join(""):"<p>Chưa có tài khoản đăng ký.</p>"}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
const noticeNames={hospital_shift:"Trực viện",donation_site:"Trực điểm hiến máu",general:"Thông báo chung"};
async function loadNotifications(){const rows=await request("/rest/v1/announcements?select=*&order=created_at.desc&limit=100");$("#notificationList").innerHTML=rows.length?rows.map(n=>`<article class="notice ${n.type}"><div><span>${noticeNames[n.type]||"Thông báo"}</span><time>${n.event_time?new Date(n.event_time).toLocaleString("vi-VN"):""}</time></div><h3>${escapeHtml(n.title)}</h3>${n.location?`<b>📍 ${escapeHtml(n.location)}</b>`:""}<p>${escapeHtml(n.content)}</p>${window.canManageMembers?`<button data-delete-notice="${n.id}">Xóa</button>`:""}</article>`).join(""):"<p>Chưa có thông báo.</p>";$("#notificationBadge").textContent="0";localStorage.setItem(`noticeSeen-${session.user.id}`,new Date().toISOString())}
async function refreshNotificationBadge(){try{const rows=await request("/rest/v1/announcements?select=id,created_at&order=created_at.desc&limit=100"),seen=localStorage.getItem(`noticeSeen-${session.user.id}`)||"1970-01-01";$("#notificationBadge").textContent=rows.filter(n=>n.created_at>seen).length}catch{$("#notificationBadge").textContent="0"}}
window.cloudSaveManagerProfile=async data=>{await request("/rest/v1/rpc/update_own_manager_profile",{method:"POST",body:JSON.stringify({p_display_name:data.name,p_student_id:data.studentId,p_class_name:data.className,p_faculty:data.faculty,p_phone:data.phone,p_photo:data.photo||null,p_membership:data.membership})});profile.display_name=data.name;const manager=window.approvedManagerProfiles.find(x=>x.user_id===session.user.id);if(manager)Object.assign(manager,{display_name:data.name,student_id:data.studentId,class_name:data.className,faculty:data.faculty,phone:data.phone,photo:data.photo||null,membership:data.membership});const roleName={leader:"Nhóm trưởng",deputy:"Nhóm phó"}[profile.role]||"Tài khoản";$("#accountInfo").textContent=`${data.name} · ${roleName}`};
window.cloudSave=async members=>{if(!session)return;try{if(!window.canManageMembers){const own=members.find(m=>m.authUserId===session.user.id);if(own)await request(`/rest/v1/members?auth_user_id=eq.${session.user.id}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({name:own.name,student_id:own.studentId,class_name:own.className,faculty:own.faculty,phone:own.phone,photo:own.photo||null})});return}const rows=members.map(m=>({id:m.id,name:m.name,student_id:m.studentId,role:m.role,membership:m.membership,class_name:m.className,faculty:m.faculty,phone:m.phone,photo:m.photo||null,auth_user_id:m.authUserId||null,invite_code:m.inviteCode||crypto.randomUUID().slice(0,8).toUpperCase(),updated_by:session.user.id}));if(rows.length)await request("/rest/v1/members?on_conflict=id",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(rows)});const cloud=await request("/rest/v1/members?select=id"),ids=new Set(members.map(m=>m.id));for(const row of cloud)if(!ids.has(row.id))await request(`/rest/v1/members?id=eq.${row.id}`,{method:"DELETE",headers:{Prefer:"return=minimal"}})}catch(error){alert(`Chưa đồng bộ được dữ liệu: ${error.message}`)}};
$("#showLogin").onclick=()=>{$("#loginForm").hidden=false;$("#registerForm").hidden=true;$("#showLogin").classList.add("active");$("#showRegister").classList.remove("active");message("")};
$("#showRegister").onclick=()=>{$("#loginForm").hidden=true;$("#registerForm").hidden=false;$("#showRegister").classList.add("active");$("#showLogin").classList.remove("active");message("")};
$("#loginForm").addEventListener("submit",async e=>{e.preventDefault();if(!configured())return message("Chưa cấu hình Supabase. Xem HUONG-DAN-SUPABASE.md.");message("Đang đăng nhập...");try{await signIn($("#loginEmail").value.trim(),$("#loginPassword").value);message("")}catch(error){message(error.message)}});
function toggleMemberFields(){const member=$("#registerRole").value==="member",box=$("#memberRegistrationFields");box.hidden=!member;for(const id of ["#registerStudentId","#registerClass","#registerFaculty","#registerPhone"])$(id).required=member&&!$("#registerInviteCode").value.trim()}
$("#registerRole").addEventListener("change",toggleMemberFields);$("#registerInviteCode").addEventListener("input",toggleMemberFields);toggleMemberFields();
$("#registerForm").addEventListener("submit",async e=>{e.preventDefault();if(!configured())return message("Chưa cấu hình Supabase.");message("Đang gửi đăng ký...");try{const role=$("#registerRole").value,extra=role==="member"?{invite_code:$("#registerInviteCode").value.trim().toUpperCase(),student_id:$("#registerStudentId").value.trim(),class_name:$("#registerClass").value.trim(),faculty:$("#registerFaculty").value.trim(),phone:$("#registerPhone").value.trim()}:{manager_invite_token:managerInviteToken},result=await signUp($("#registerName").value.trim(),$("#registerEmail").value.trim(),$("#registerPassword").value,role,extra);e.target.reset();toggleMemberFields();message(role==="member"?(result.session?"Đăng ký và liên kết nhóm thành công. Bạn có thể đăng nhập ngay.":"Đăng ký thành công. Hãy xác nhận email rồi đăng nhập."):(managerInviteToken?"Đăng ký qua link mời thành công. Bạn có thể đăng nhập.":result.session?"Đăng ký thành công. Hãy chờ admin duyệt.":"Đăng ký thành công. Hãy xác nhận email rồi chờ admin duyệt."),true)}catch(error){message(error.message)}});
$("#adminButton").onclick=async()=>{$("#adminDialog").showModal();$("#accountList").innerHTML="<p>Đang tải...</p>";try{await loadAccounts()}catch(e){$("#accountList").textContent=e.message}};
$("#closeAdmin").onclick=()=>$("#adminDialog").close();
$("#accountList").onclick=async e=>{const button=e.target.closest("[data-account]");if(!button)return;button.disabled=true;try{await request(`/rest/v1/manager_profiles?user_id=eq.${button.dataset.account}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({status:button.dataset.status,reviewed_by:session.user.id,reviewed_at:new Date().toISOString()})});await loadAccounts()}catch(error){alert(error.message);button.disabled=false}};
async function createManagerInvite(role){const token=crypto.randomUUID().replaceAll("-","").slice(0,24),expires=new Date(Date.now()+7*864e5).toISOString();try{await request("/rest/v1/manager_invites",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({token,role,created_by:session.user.id,expires_at:expires})});const url=`${location.origin}${location.pathname}?manager_invite=${token}&role=${role}`;$("#managerInviteLink").value=url;await navigator.clipboard?.writeText(url);alert("Đã tạo và sao chép link mời") }catch(error){alert(error.message)}}
$("#createLeaderInvite").onclick=()=>createManagerInvite("leader");$("#createDeputyInvite").onclick=()=>createManagerInvite("deputy");$("#copyManagerInvite").onclick=async()=>{const value=$("#managerInviteLink").value;if(!value)return;await navigator.clipboard.writeText(value);alert("Đã sao chép link")};
$("#notificationButton").onclick=async()=>{$("#notificationDialog").showModal();$("#notificationList").innerHTML="<p>Đang tải...</p>";try{await loadNotifications()}catch(e){$("#notificationList").textContent=e.message}};
$("#closeNotifications").onclick=()=>$("#notificationDialog").close();
$("#notificationForm").addEventListener("submit",async e=>{e.preventDefault();try{const notice={title:$("#noticeTitle").value.trim(),content:$("#noticeContent").value.trim(),type:$("#noticeType").value,location:$("#noticeLocation").value.trim()||null,event_time:$("#noticeTime").value?new Date($("#noticeTime").value).toISOString():null,created_by:session.user.id};await request("/rest/v1/announcements",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify(notice)});await window.sendPhonePush(notice);e.target.reset();await loadNotifications();alert("Đã gửi thông báo đến điện thoại đã đăng ký.")}catch(error){alert("Thông báo đã lưu trong app nhưng chưa gửi được về điện thoại: "+error.message)}});
$("#notificationList").onclick=async e=>{const button=e.target.closest("[data-delete-notice]");if(!button||!confirm("Xóa thông báo này?"))return;try{await request(`/rest/v1/announcements?id=eq.${button.dataset.deleteNotice}`,{method:"DELETE",headers:{Prefer:"return=minimal"}});await loadNotifications()}catch(error){alert(error.message)}};
$("#signOutButton").addEventListener("click",async()=>{try{if(session)await request("/auth/v1/logout",{method:"POST"})}catch{}localStorage.removeItem(sessionKey);location.reload()});
(function prepareManagerInvite(){if(!managerInviteToken||!["leader","deputy"].includes(managerInviteRole))return;$("#showRegister").click();$("#registerRole").value=managerInviteRole;$("#registerRole").disabled=true;toggleMemberFields();const note=document.createElement("p");note.className="invite-registration-note";note.textContent=`Link mời ${managerInviteRole==="leader"?"Nhóm trưởng":"Nhóm phó"} hợp lệ. Tài khoản sẽ được kích hoạt sau khi đăng ký.`;$("#registerForm").prepend(note)})();
(async()=>{if(!configured())return message("Cần cấu hình Supabase trước khi đăng nhập.");try{session=JSON.parse(localStorage.getItem(sessionKey));if(session?.access_token)await enterApp()}catch(error){localStorage.removeItem(sessionKey);message(error.message)}})();
}
